export const jobs = [
  {
    id: 1,
    title: 'Desarrollador Senior Blockchain',
    company: 'CryptoTech España',
    location: 'madrid',
    displayLocation: 'Madrid, España (Remoto)',
    salary: '€65,000 - €85,000',
    type: 'Tiempo Completo',
    tags: ['Solidity', 'Ethereum', 'Smart Contracts'],
    featured: true,
    description: 'Buscamos un desarrollador senior de blockchain para liderar el desarrollo de contratos inteligentes y aplicaciones descentralizadas. El candidato ideal tiene experiencia sólida en Ethereum y desarrollo de DApps.',
    requirements: [
      'Más de 5 años de experiencia en desarrollo de software',
      'Experiencia demostrable con Solidity y Smart Contracts',
      'Conocimiento profundo de la blockchain de Ethereum y sus estándares',
      'Experiencia con Web3.js o Ethers.js',
      'Familiaridad con patrones de seguridad en Smart Contracts',
    ],
    benefits: [
      'Trabajo 100% remoto',
      'Horario flexible',
      'Seguro médico privado',
      'Presupuesto para formación',
      '25 días de vacaciones',
    ],
    contactEmail: 'careers@cryptotech.es',
  },
  {
    id: 2,
    title: 'Arquitecto DeFi',
    company: 'BlockChain Solutions',
    location: 'barcelona',
    displayLocation: 'Barcelona, España',
    salary: '€70,000 - €90,000',
    type: 'Tiempo Completo',
    tags: ['DeFi', 'Web3.js', 'Solidity'],
    featured: true,
    description: 'Únete a nuestro equipo como Arquitecto DeFi para diseñar y desarrollar protocolos financieros descentralizados innovadores. Trabajarás en proyectos de vanguardia en el espacio DeFi.',
    requirements: [
      'Experiencia en arquitectura de sistemas DeFi',
      'Conocimiento profundo de protocolos DeFi existentes',
      'Experiencia en desarrollo de Smart Contracts',
      'Comprensión de tokenomics y mecanismos de incentivos',
    ],
    benefits: [
      'Oficina en el centro de Barcelona',
      'Opción de trabajo híbrido',
      'Stock options',
      'Seguro médico y dental',
    ],
    contactEmail: 'talent@blockchainsolutions.es',
  },
  {
    id: 3,
    title: 'Desarrollador Web3 Junior',
    company: 'Crypto Startup',
    location: 'valencia',
    displayLocation: 'Valencia, España (Híbrido)',
    salary: '€35,000 - €45,000',
    type: 'Tiempo Completo',
    tags: ['JavaScript', 'React', 'Web3'],
    description: 'Buscamos un desarrollador junior apasionado por Web3 para unirse a nuestro equipo en crecimiento. Es una oportunidad perfecta para adentrarse en el mundo blockchain.',
    requirements: [
      'Conocimientos de JavaScript y React',
      'Interés demostrable en tecnología blockchain',
      'Capacidad de aprendizaje rápido',
      'Nivel alto de inglés',
    ],
    benefits: [
      'Mentoring personalizado',
      'Trabajo híbrido (2 días remotos)',
      'Eventos y conferencias',
      'Ambiente startup dinámico',
    ],
    contactEmail: 'jobs@cryptostartup.es',
  },
];